# Generated by Django 6.0.3 on 2026-03-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('classes_attended', models.IntegerField()),
                ('total_classes', models.IntegerField()),
            ],
        ),
    ]
